#!/bin/bash

# reference
# https://www.howtoforge.com/tutorial/how-to-enable-ssl-and-remote-connections-for-mysql-on-centos-7/

mkdir -p /var/lib/mysql/mysql-certs
cd /var/lib/mysql/mysql-certs

openssl genrsa 2048 > ca-key.pem
openssl req -new -x509 -nodes -days 3600 -key ca-key.pem -out ca.pem
openssl req -newkey rsa:2048 -days 3600 -nodes -keyout server-key.pem -out server-req.pem
openssl rsa -in server-key.pem -out server-key.pem
openssl x509 -req -in server-req.pem -days 3600 -CA ca.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.pem
openssl req -newkey rsa:2048 -days 3600 -nodes -keyout client-key.pem -out client-req.pem
openssl rsa -in client-key.pem -out client-key.pem
openssl x509 -req -in client-req.pem -days 3600 -CA ca.pem -CAkey ca-key.pem -set_serial 01 -out client-cert.pem
openssl verify -CAfile ca.pem server-cert.pem client-cert.pem

chown -R mysql:mysql /var/lib/mysql/mysql-certs
chmod 600 client-key.pem server-key.pem ca-key.pem

echo "[mysqld] \
ssl-ca=/var/lib/mysql/mysql-certs/ca.pem \
ssl-cert=/var/lib/mysql/mysql-certs/server-cert.pem \
ssl-key=/var/lib/mysql/mysql-certs/server-key.pem \

[client] \
ssl-ca=/var/lib/mysql/mysql-certs/ca.pem \
ssl-cert=/var/lib/mysql/mysql-certs/client-cert.pem \
ssl-key=/var/lib/mysql/mysql-certs/client-key.pem \
"

# /etc/my.cnf configs
# bind-address = *
# require_secure_transport = ON

